baseurl = "https://shayananique.com"
title = "Shayan Anique Akhtar"
theme = "hugo-coder"
languagecode = "en-us"
defaultcontentlanguage = "en-us"

googleAnalytics = "G-8641XM5V8K"

paginate = 20
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
enableRobotsTXT = true

[params]
  author = "Shayan Anique Akhtar"
  info = "Cyber Security Researcher, Teacher, Breaking and Making Things."
  description = "Making and Breaking Things."
  keywords = "technologist,cybersec,infosec,programmer"
  #avatarurl = "images/avatar.jpg"

  #gravatar = "shayan@shayananique.com"

  #enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
 url = "https://github.com/shayananique/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/shayananique/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/shayan_anique/"

#[[params.social]]
#  name = "RSS"
#  icon = "fa fa-2x fa-rss"
#  weight = 6
#  url = "https://shayananique.com/index.xml"
#  rel = "alternate"
#  type = "application/rss+xml"

# Menu links
#[[menu.main]]
#  name = "Blog"
#  weight = 1
#  url  = "posts/"
[[menu.main]]
  name = "Contact"
  weight = 2
  url = "contact/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
#[[menu.main]]
#  name = "Press"
#  weight = 2
#  url = "press/"
[[menu.main]]
  name = "Privacy"
  weight = 2
  url = "privacy/"
