baseurl = "https://shayananique.com"
defaultcontentlanguage = "en-us"
languagecode = "en-us"
theme = "hugo-coder"
title = "Shayan Anique"

paginate = 20

pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "bw"

[params]
author = "Shayan Anique"
description = "Making and Breaking Things."
info = "Cyber Security Researcher"
keywords = "technologist,cybersec,infosec,coder"


[params.googleTagManager]
id = "G-Y9ESF0K5GG"

colorScheme = "auto"
#favicon_32 = "/images/favicon-32x32.png"
hidecolorschemetoggle = false


[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
icon = "fa fa-github fa-2x"
name = "Github"
url = "https://github.com/shayananique/"
weight = 1

[[params.social]]
icon = "fa fa-gitlab fa-2x"
name = "Gitlab"
url = "https://gitlab.com/shayananique/"
weight = 2

[[params.social]]
icon = "fa fa-twitter fa-2x"
name = "Twitter"
url = "https://twitter.com/shayan_anique/"
weight = 3

[[params.social]]
name = "RSS"
icon = "fa fa-2x fa-rss"
weight = 6
url = "https://shayananique.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

# Menu links
[[menu.main]]
name = "Blog"
url = "posts/"
weight = 1
[[menu.main]]
name = "Contact me"
url = "contact/"
weight = 2